site_name: Youtube

repo_name: '2022.1-Youtube'
repo_url: 'https://github.com/Requisitos-de-Software/2022.1-Youtube'

theme:
  name: material
  language: 'pt'
  logo: 'media/logo-youtube.png'
  palette:
    primary: 'red'


nav: 
  - Página Inicial: index.md
  - Planejamento:
    - Planejamento: planejamento/planejamento.md
    - Ferramentas: planejamento/ferramentas.md
    - Cronograma: planejamento/cronograma.md
  - Rich Picture: richpicture.md
  - Apresentações: apresentacao.md