site_name: Youtube

repo_name: '2022.1-Youtube'
repo_url: 'https://github.com/Requisitos-de-Software/2022.1-Youtube'

theme:
  name: material
  language: 'pt'
  logo: 'media/logo-youtube.png'
  palette:
    primary: 'red'

nav: 
  - Página Inicial: index.md
  - Planejamento:
    - Planejamento: planejamento/planejamento.md
    - Ferramentas: planejamento/ferramentas.md
    - Cronograma: planejamento/cronograma.md
  - Rich Picture: richpicture.md
  - Elicitação:
    - Personas: elicitacao/personas.md
    - Perfil de Usuário: elicitacao/perfil.md
    - Técnicas:
      - Brainstorm: elicitacao/tecnicas/brainstorm.md
      - Introspecção: elicitacao/tecnicas/introspeccao.md
      - Observação: elicitacao/tecnicas/observacao.md
      - Entrevista: elicitacao/tecnicas/entrevista.md
    - Priorização:
      - MoSCoW: elicitacao/priorizacao/moscow.md
      - 100 Dólares: elicitacao/priorizacao/100dol.md
    - Resultado Elicitação: elicitacao/resultado.md
  - Modelagem:
    - Cenários: modelagem/cenarios.md
    - Léxicos:
      - Estado: modelagem/lexicos/estado.md
      - Objeto: modelagem/lexicos/objeto.md
      - Verbo: modelagem/lexicos/verbo.md
    - Casos de Uso: modelagem/casouso.md
    - Especificação Suplementar: modelagem/espsup.md
    - Ágil:
      - Backlog do Produto + Histórias de Usuário: modelagem/backlog.md
  - Apresentações: apresentacao.md